<?php
$pageTitle = 'Secret Audit';
require_once __DIR__ . '/_header.php';

// simple pagination
$page = max(1, intval($_GET['page'] ?? 1));
$perPage = 25;
$offset = ($page - 1) * $perPage;

$stmt = $pdo->prepare('SELECT SQL_CALC_FOUND_ROWS id, pkfk_station, generated_by, event, generated_at, meta FROM secret_audit ORDER BY generated_at DESC LIMIT ? OFFSET ?');
$stmt->bindValue(1, (int)$perPage, PDO::PARAM_INT);
$stmt->bindValue(2, (int)$offset, PDO::PARAM_INT);
$stmt->execute();
$rows = $stmt->fetchAll();
$totalRow = $pdo->query('SELECT FOUND_ROWS() as total')->fetch();
$total = $totalRow ? intval($totalRow['total']) : count($rows);
$pages = max(1, ceil($total / $perPage));
?>

<div class="container">
    <h1>Secret Generation Audit</h1>
    <p>Monitor secret generation and revelation events for security auditing.</p>

    <div class="card">
        <h3>Export Audit Data</h3>
        <form method="post" action="export_secret_audit.php">
            <div class="form-group">
                <label for="station">Station Serial</label>
                <input type="text" name="station" id="station" placeholder="e.g., STATION001">
            </div>
            <div class="form-group">
                <label for="event">Event Type</label>
                <select name="event" id="event">
                    <option value="">Any Event</option>
                    <option value="generated">Generated</option>
                    <option value="revealed">Revealed</option>
                </select>
            </div>
            <div class="form-group">
                <label for="from">From Date</label>
                <input type="datetime-local" name="from" id="from">
            </div>
            <div class="form-group">
                <label for="to">To Date</label>
                <input type="datetime-local" name="to" id="to">
            </div>
            <?php echo csrf_input(); ?>
            <button type="submit" class="btn">Export CSV</button>
        </form>
    </div>

    <div class="card">
        <h3>Audit Events</h3>
        <p>Page <?php echo $page; ?> of <?php echo $pages; ?> (<?php echo number_format($total); ?> total events)</p>

        <?php if (empty($rows)): ?>
            <p>No audit events found.</p>
        <?php else: ?>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Station</th>
                        <th>Generated By</th>
                        <th>Event</th>
                        <th>Timestamp</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($rows as $row): ?>
                        <tr>
                            <td><code><?php echo htmlspecialchars($row['id']); ?></code></td>
                            <td><code><?php echo htmlspecialchars($row['pkfk_station']); ?></code></td>
                            <td><?php echo htmlspecialchars($row['generated_by']); ?></td>
                            <td><?php echo htmlspecialchars($row['event']); ?></td>
                            <td><?php echo htmlspecialchars($row['generated_at']); ?></td>
                            <td>
                                <?php
                                $meta = json_decode($row['meta'], true);
                                if ($meta && isset($meta['ip'])) {
                                    echo 'IP: ' . htmlspecialchars($meta['ip']);
                                } else {
                                    echo 'No details';
                                }
                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <?php if ($pages > 1): ?>
                <p>
                    <?php if ($page > 1): ?>
                        <a href="?page=<?php echo $page - 1; ?>" class="btn btn-small">Previous</a>
                    <?php endif; ?>
                    <?php if ($page < $pages): ?>
                        <a href="?page=<?php echo $page + 1; ?>" class="btn btn-small">Next</a>
                    <?php endif; ?>
                </p>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
</body>
</html>

